MDFloatLayout:
    MDLabel:
        id: task_label
        halign: 'center'
        markup: True
        text: "[u][size=48][b]WorkWise[/b][/size][/u]"
        pos_hint: {'y': .45}

    ScrollView:
        pos_hint: {'center_y': .5, 'center_x': .5}
        size_hint: .9, .8

        MDList:
            id: container

    MDIconButton:
        id: menu_btn  # Thêm định nghĩa cho nút Menu với id là 'menu_btn'
        icon: "menu"
        pos_hint: {'x': 0.02, 'top': 0.95}  # Đặt nút Menu ở góc trái phía trên
        on_release: app.show_menu()  # Khi nhấp vào nút Menu, gọi phương thức show_menu() của lớp MainApp
        md_bg_color: app.theme_cls.primary_color  # Đặt màu xanh cho nút menu

    MDFloatingActionButton:
        icon: 'plus-thick'
        on_release: app.show_task_dialog()
        elevation_normal: 12
        pos_hint: {'x': .45 , 'y': .04}
        md_bg_color: app.theme_cls.primary_color  # Đặt màu xanh cho nút thêm nhiệm vụ

<DialogContent>:
    orientation: "vertical"
    spacing: "10dp"
    size_hint: 1, None
    height: "240dp"

    MDTextField:
        id: task_text
        hint_text: "Add Task..."
        pos_hint: {"center_y": .9}
        max_text_length: 50
        on_text_validate: (app.add_task(task_text.text, date_text.text, time_text.text), app.close_dialog())

    GridLayout:
        cols: 2
        spacing: "10dp"

        MDIconButton:
            icon: 'calendar'
            on_release: root.show_date_picker()

        MDIconButton:
            id: time_btn
            icon: 'clock'
            on_release: root.show_time_picker()

    MDLabel:
        id: date_text
        pos_hint: {"center_y": .5}

    MDLabel:
        id: time_text
        pos_hint: {"center_y": .5}

    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: None
        height: "36dp"

        MDRaisedButton:
            text: "SAVE"
            disabled: time_text.text == ""  # Disable nút SAVE nếu chưa nhập thời gian
            on_release: app.add_task(task_text.text, date_text.text, time_text.text); app.close_dialog()

        MDFlatButton:
            text: 'CANCEL'
            on_release: app.close_dialog()

<DialogEdit>:
    orientation: "vertical"
    spacing: "10dp"
    size_hint: 1, None
    height: "300dp"

    MDTextField:
        id: edit_task_text
        hint_text: "Edit Task..."
        pos_hint: {"center_y": .9}
        max_text_length: 50
        on_text_validate: app.edit_task(edit_task_text.text, edit_date_text.text, edit_time_text.text, the_list_item.pk); app.close_dialog()

    GridLayout:
        cols: 2
        spacing: "10dp"

        MDIconButton:
            icon: 'calendar'
            on_release: root.show_date_picker()

        MDIconButton:
            id: time_btn
            icon: 'clock'
            on_release: root.show_time_picker()

    MDLabel:
        id: edit_date_text
        pos_hint: {"center_y": .5}

    MDLabel:
        id: edit_time_text
        pos_hint: {"center_y": .5}

    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: None
        height: "36dp"

        MDRaisedButton:
            text: "SAVE"
            on_release: app.edit_task(edit_task_text.text, edit_date_text.text, edit_time_text.text, root.list_item.pk); app.close_edit_dialog()

        MDFlatButton:
            text: 'CANCEL'
            on_release: app.close_edit_dialog()

<ListItemWithCheckbox>:
    id: the_list_item
    markup: True

    LeftCheckbox:
        id: check
        on_active:
            app.on_checkbox_active(check, check.active, the_list_item) if check.active else \
            app.on_checkbox_deactivate(check, check.active, the_list_item)
    IconRightWidget:
        icon: "pencil"
        theme_text_color: "Custom"
        text_color: 0, 0, 0, 1
        on_release: app.show_edit_dialog(the_list_item)
    IconRightWidget:
        icon: 'trash-can-outline'
        theme_text_color: "Custom"
        text_color: 1, 0, 0, 1
        on_release: app.delete_item(the_list_item)
